### ISSUE TITLE
Status on Model Weight Release?

### ISSUE THREAD

**Issue by norsedrunkensailor** [amyxlu/cheap-proteins#2]
Dear Amy,

Love your work on this and super excited to start using this framework in downstream research. What is the status on model weights being released? 

All the best,
NDS

**Comment by amyxlu** [comment]
hi, thanks for the interest in our work!

See here for the model weights: https://huggingface.co/amyxlu/cheap-proteins/tree/main. Will implement the changes to get the weights more conveniently downloadable in the coming weeks.

**Comment by norsedrunkensailor** [comment]
Hello!

Perhaps it's still private? The page is still empty in you HF profile: https://huggingface.co/amyxlu
<img width="843" alt="Screenshot 2024-10-02 at 07 46 21" src="https://github.com/user-attachments/assets/1abb441b-56ca-4eaa-a712-5d07b9eb28ca">

best<3,
NDS

**Comment by amyxlu** [comment]
Could you check to see if this works now?

https://huggingface.co/amyxlu/cheap-proteins/tree/main

**Comment by norsedrunkensailor** [comment]
It does -- Aiiiii you made our day!

All the best, 
NDS
