### ISSUE TITLE
torch.load(model_path) is returning the model object, not the state dict

### ISSUE THREAD

**Issue by kirjner** [amyxlu/cheap-proteins#4]
Hi Amy, 

First of all, thanks for the great work! 

One thing I noticed is that when I tried to run the short example with 3 sequences on the README, I got an error within `src/cheap/pretrained.py` indicating the problem listed in the title, for which I've attached a screenshot of a minimal example:

<img width="1133" alt="Screenshot 2024-10-13 at 2 40 02 PM" src="https://github.com/user-attachments/assets/c5f8fb21-dafe-4616-9621-489ed1be86bd">

Is it possible that when saving to HF, `torch.save(model, path)` was run, rather than `torch.save(model.state_dict(), path)`? 

Best,
Andrew

**Comment by amyxlu** [comment]
Hi @kirjner, thanks for pointing me to this! I just fixed the checkpoints -- let me know if you're still having issues.
